/*
 * This source file was generated by the Gradle 'init' task
 */
package playwrightBase;

import com.microsoft.playwright.Browser;
import com.microsoft.playwright.BrowserType;
import com.microsoft.playwright.Page;
import com.microsoft.playwright.Playwright;
import org.junit.Test;

public class PlaywrightBase {

    @Test
    public void testGoogle() {
        try (Playwright playwright = Playwright.create()) {
            Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions().setHeadless(false));
            Page page = browser.newPage();
            page.navigate("https://www.google.com");
            System.out.println("Title: " + page.title());
            browser.close();
        }
    }
}
